### PR TITLE
chore: enable auto-publish

### PR DESCRIPTION
**Pull request by marcoscaceres**
W3C is moving off travisci. This does what the old travis script used to do. 

@siusin, @johanneswilm, I've set it to CC you if publication fails.

### CODE REVIEW

**Comment by siusin** [comment]
It's failing because we need to publish this spec manually in the Editing WG before we set up auto-publication. Echidna could not handle the change of the group.

It's on my to-do list. Thanks @marcoscaceres for the PR.

**Comment by travisleithead** [comment]
@siusin, as a new WG, do we need to go through the process of issuing a FPWD for input events, despite the fact that it was published by the WebApps WG as a WD here: https://www.w3.org/TR/input-events-1/ ? By the process, I think the answer is 'yes' but need your advice.

**Comment by siusin** [comment]
> @siusin, as a new WG, do we need to go through the process of issuing a FPWD for input events, despite the fact that it was published by the WebApps WG as a WD here: https://www.w3.org/TR/input-events-1/ ? By the process, I think the answer is 'yes' but need your advice.

No, we don't need to publish an FPWD, but we do need to publish a new WD manually because our auto-publish system can't handle a spec that changes its WG. 

I heard that the plan was to drop Level1 and update a few things in Level2, if that's the case, do you think we can go back to  /TR/input-event/ for the future WDs? (instead of /TR/input-event-2/ )

**Comment by marcoscaceres** [comment]
Dropping versioning/levels would be amazing 🙏

**Comment by johanneswilm** [comment]
Hey,
yes, moving ahead with only level 2 is what we have agreed to do. The background is this: We split the spec into two levels because the Chromium team announced that they could only ship some of the features of the spec and they would ship nothing at all if there was not a spec that would match the features they were shipping. The full spec then became level 2 (implemented by Webkit) and the part the Chromium team shipped was level 1.

In connection with the Mozilla team implementing the beforeinput event, we then later found out that some other people within the Chromium team who had not been part of the process implemented and shipped most of level 2 anyway. So now level 1 is less than what is shipped by any of the browser.

However, there are still some things in level 2 (related to IME) that have not been shipped in Chromium. It is now the Microsoft team working on, and in particular @BoCupp-Microsoft, who will have to tell us which parts of the remaining parts of level 2 they can be implemented and shipped with Chromium. We have then agreed that the remaining features in level 2 that have been shipped in at least Webkit but that cannot be shipped with Chromium will be marked as optional in level 2. At that stage level 2 should be the only version moving forward.

@BoCupp-Microsoft do you think we can get an answer on that question within a resonable timeframe? If that is the case, then I would say yes, let's wait for that and move directly ahead with level 2. However, if it will take months and years and we might potentially never receive a clear answer on that question, then we should probably count on continuing with two different levels for the time being.

**Comment by travisleithead** [comment]
WG Call: We will defer deciding this for another month to give @BoCupp-Microsoft a bit more time.

**Comment by BoCupp-Microsoft** [comment]
@johanneswilm @travisleithead following up on the question for me above, I have [prepared a PR](https://github.com/w3c/input-events/pull/122) for input events level 2 that removes beforeinput/input events for the inputTypes insertFromComposition, deleteByComposition and deleteCompositionText.  I'll say more in the comments of that PR about the rationale for the change, but if we agree that this is an acceptable scoping of level 2 then I don't believe we  need separate levels.

**Comment by johanneswilm** [comment]
Hey @BoCupp-Microsoft , I thought you were going to create a PR to mark those parts of level 2 you cannot implement in Chromium as optional - not remove them. I don't think we should remove them as they continue to be the best possible way of solving the issue that we currently know about and it has been implemented and shipped for several years in Webkit.

**Review by siusin — APPROVED** [review]

**Comment by siusin** [comment]
Further changes might be need once we publish Input Events as a WD

**Pull request merged**
