### PR TITLE
minor typo

### PR DESCRIPTION
**Pull request by dret**

### CODE REVIEW

**Comment by dret** [comment]
sorry if this is a duplicate. i am having naming confusion. on the w3c site, two specs and documents show up. but there only is one in the repo?

**Comment by johanneswilm** [comment]
One repo with two branches (v1 and gh-pages)

**Comment by chaals** [comment]
Marked as non-substantive for IPR from ash-nazg.

**Comment by dret** [comment]
ok. i guess in that case i can close this PR as being a duplicate of #56.

**Pull request merged**
