### PR TITLE
link to grapheme definition in i18n-glossary, fixes #73

### LINKED ISSUE #73: "character" is not defined
[from Addison Phillips]

https://w3c.github.io/input-events/#interface-InputEvent-Attributes

In section 5.1.2 there are multiple places where the term "character" is used without definition. It would be better to clearly define this to mean a Unicode code point.

### PR DESCRIPTION
**Pull request by johanneswilm**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/input-events/pull/139.html" title="Last updated on Sep 13, 2023, 6:21 PM UTC (0d026c9)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/input-events/139/e3d8bbd...0d026c9.html" title="Last updated on Sep 13, 2023, 6:21 PM UTC (0d026c9)">Diff</a>

### CODE REVIEW

**Comment by johanneswilm** [comment]
@aphillips This PR adds the link as you suggested. Note though that it introduces a ReSpec warning: The definition in the i18n-glossary is only informative, but we need it here in a normative context. Would it be possible to change the definition in the i18n-glossary to become normative or would you advise something else?

**Review by aphillips — APPROVED** [review]
This looks okay, although you might want to point to the definition `[grapheme cluster](https://www.w3.org/TR/i18n-glossary/#def_grapheme_cluster)` for its higher level of specificity.

We've never had a problem with definitions from our glossary being "non-normative" (presumably because the glossary is a Note rather than being on the Rec track??). One reason for the glossary is to avoid specifications (such as yours) creating divergent definitions (such as when you previously defined `character`) or needing to provide your readers with a tutorial on the dense thicket of jargon in the character encoding space. There isn't really a "more normative reference source".

**Comment by johanneswilm** [comment]
@aphillips To me, actually your initial recommendation of linking to the definition of "grapheme" feels more accurate as we are referring to as something that is perceived as being a character by the user. But I'll be happy to replace "grapheme" with "grapheme cluster" if you think that is more accurate.

**Comment by johanneswilm** [comment]
@aphillips I have asked the Respec experts for help on this. Hopefully they have a solution.

**Comment by aphillips** [comment]
@johanneswilm I would prefer the `grapheme` definition, but your original text was more specific (via the `character` definition) in referring explicitly to UAX29's definition of extended grapheme clusters. Our `grapheme cluster` definition provides that level of specificity whereas our `grapheme` one isn't quite so clear. We might add some text to `grapheme` to make it clearer and that's probably a good idea. I'd prefer to reduce the level of opaque jargon overall and avoiding the word "cluster" would be good.

On the Respec thing, let me know what you find out (or copy me!! I'm obviously ***super*** interested)

**Pull request merged**
